DROP TABLE libraries;
DROP TABLE reservation;
DROP TABLE routes;
DROP TABLE bibuseros;
DROP TABLE comments;
DROP TABLE sanctions;
DROP TABLE loans;
DROP TABLE users;
DROP TABLE bibuses;
DROP TABLE municipalities;
DROP TABLE copies;
DROP TABLE publications;
DROP TABLE contributions;
DROP TABLE books;
DROP TABLE authors;

CREATE TABLE authors (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    main_author VARCHAR2(255) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    surname VARCHAR2(255) NOT NULL,
    birth_year NUMBER NULL,
    death_year NUMBER NULL
);

CREATE TABLE books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    author_id NUMBER NOT NULL REFERENCES authors(id),
    pub_country VARCHAR2(255) NOT NULL,
    pub_date NUMBER(4) NOT NULL,
    alternative_titles VARCHAR2(255) NOT NULL,
    subject VARCHAR2(255) NOT NULL,
    content_note VARCHAR2(2500) NOT NULL,
    awards VARCHAR2(255) NOT NULL
);

CREATE TABLE contributions (
    author_id NUMBER REFERENCES authors(id),
    book_id NUMBER REFERENCES books(id),
    mention VARCHAR2(255) NOT NULL,
    PRIMARY KEY (author_id, book_id)
);

CREATE TABLE publications (
    isbn NUMBER PRIMARY KEY,
    book_id NUMBER NOT NULL REFERENCES books(id),
    main_language VARCHAR2(50) NOT NULL,
    other_languages VARCHAR2(50) NOT NULL,
    edition VARCHAR2(50) NOT NULL,
    publisher VARCHAR2(255) NOT NULL,
    length NUMBER NOT NULL,
    series VARCHAR2(50) NOT NULL,
    legal_deposit VARCHAR2(50) NOT NULL,
    publication_place VARCHAR2(50) NOT NULL,
    dimensions VARCHAR2(50) NOT NULL,
    physical_chars VARCHAR2(255) NOT NULL,
    additional_material VARCHAR2(255) NULL,
    national_id NUMBER NOT NULL UNIQUE,
    url VARCHAR2(255) NOT NULL
);

CREATE TABLE copies (
    id NUMBER PRIMARY KEY,
    publication_id NUMBER NOT NULL,
    condition VARCHAR2(255) NOT NULL,
    comments VARCHAR2(500) NOT NULL,
    available NUMBER(1) NOT NULL,
    derregistration_date DATE NULL
);

CREATE TABLE municipalities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    population NUMBER NOT NULL,
    has_library NUMBER(1) NOT NULL
);

CREATE TABLE bibuses (
    plate VARCHAR2(255) PRIMARY KEY,
    last_itv DATE NOT NULL,
    next_itv DATE NOT NULL,
    state VARCHAR2(255) NOT NULL
);

CREATE TABLE users (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    surname1 VARCHAR2(255) NOT NULL,
    surname2 VARCHAR2(255) NOT NULL,
    passport NUMBER NOT NULL UNIQUE,
    birthdate DATE NOT NULL,
    town VARCHAR2(255) NOT NULL,
    municipality_id NUMBER NOT NULL REFERENCES municipalities(id),
    address VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NULL,
    telephone NUMBER NOT NULL,
    user_type VARCHAR2(255) NOT NULL
);

CREATE TABLE loans (
    id NUMBER PRIMARY KEY,
    start_date DATE NOT NULL,
    return_date DATE NOT NULL,
    user_id NUMBER NOT NULL REFERENCES users(id),
    copy_id NUMBER NOT NULL REFERENCES copies(id)
);

CREATE TABLE sanctions (
    id NUMBER PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id),
    loan_id NUMBER NOT NULL REFERENCES loans(id),
    weeks NUMBER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL
);

CREATE TABLE comments (
    id NUMBER PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id),
    comment_date DATE NOT NULL,
    book_id NUMBER NOT NULL REFERENCES books(id),
    copy_id NUMBER NOT NULL REFERENCES copies(id),
    body VARCHAR2(500) NOT NULL,
    likes NUMBER NOT NULL,
    dislikes NUMBER NOT NULL
);

CREATE TABLE bibuseros (
    passport VARCHAR2(255) PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    surname VARCHAR2(255) NOT NULL,
    telephone NUMBER NOT NULL,
    email VARCHAR2(255) NOT NULL,
    contract_start DATE NOT NULL,
    contract_end DATE NULL,
    state VARCHAR2(255) NOT NULL
);

CREATE TABLE routes (
    id NUMBER PRIMARY KEY,
    stop_day DATE NOT NULL,
    municipality_id NUMBER NOT NULL REFERENCES municipalities(id),
    bibus_id VARCHAR2(255) NOT NULL REFERENCES bibuses(plate),
    bibusero_id VARCHAR2(255) NOT NULL REFERENCES bibuseros(passport)
);

CREATE TABLE reservation (
    id NUMBER PRIMARY KEY,
    copy_id NUMBER NOT NULL REFERENCES copies(id),
    user_id NUMBER NOT NULL REFERENCES users(id),
    route_id NUMBER NOT NULL REFERENCES routes(id),
    reservation_date DATE NOT NULL,
    state VARCHAR2(255) NOT NULL        
);

CREATE TABLE libraries (
    CIF NUMBER PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    foundation_date DATE NOT NULL,
    municipality_id NUMBER NOT NULL REFERENCES municipalities(id),
    address VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    telephone NUMBER NOT NULL
);
